name: endgame_mastery
description: "Endgame Mastery interactive chess endgame trainer."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.4.2
  chess: ^0.8.1
  flutter_svg: ^2.3.0
  go_router: ^17.5.0
  collection: ^1.19.1
  just_audio: ^0.10.6
  chess_vectors_flutter: ^1.1.0
  web: ^1.1.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
