import '../domain/lesson_definition.dart';
import '../overlay/pedagogical_overlay.dart';

/// Pedagogical interpretation of one current chess position.
///
/// This is the bridge between curriculum data and the future learning UI.
///
/// It contains no Flutter widgets and no engine evaluation.
class TeachingState {
  const TeachingState({
    required this.fen,
    required this.sideToMove,
    required this.theoreticalResult,
    required this.overlay,
    required this.teachingPoint,
  });

  /// Current complete FEN.
  final String fen;

  /// Side whose turn it is in the current position.
  final ChessSide sideToMove;

  /// Known curriculum result from the learner's point of view.
  ///
  /// Null means the curriculum has not explicitly established the result
  /// for this exact position.
  ///
  /// We deliberately prefer "unknown" to inventing chess truth.
  final TheoreticalResult? theoreticalResult;

  /// Semantic board annotations generated by the pedagogical overlay engine.
  final PedagogicalOverlay overlay;

  /// Optional explanation associated with this exact theoretical position.
  final String? teachingPoint;

  Set<String> get keySquares {
    return Set<String>.unmodifiable(
      overlay.squares
          .where((square) => square.role == SquareOverlayRole.keySquare)
          .map((square) => square.square),
    );
  }

  bool get hasKnownTheoreticalResult => theoreticalResult != null;
}
