import '../domain/lesson_hints.dart';

/// Verified curriculum hints for Pawn Endgames.
///
/// These hints belong to the teaching curriculum.
/// They are not generated by Stockfish.
final LessonHints keySquaresLesson01Hints = LessonHints(
  concept:
      'A fifth-rank pawn has a six-square key-square zone. Do not assume the advanced pawn is winning if the defending king already controls that zone.',
  visual:
      'For the pawn on d5, look at c6, d6, e6, c7, d7, and e7. Black already occupies d7.',
  targeted:
      'Preserve the draw. Improve the king without allowing Black to force your king away from the pawn at the wrong moment.',
);

final LessonHints keySquaresLesson02Hints = LessonHints(
  concept:
      'A fifth-rank pawn has six key squares. If your king already occupies one, the task is conversion rather than finding the key-square zone.',
  visual:
      'For the pawn on b5, the key squares are a6, b6, c6, a7, b7, and c7. Your king is already standing on b6.',
  targeted:
      'Use the king to make progress before pushing the pawn. Keep stalemate resources in mind when the black king is trapped near a8.',
);

final LessonHints keySquaresLesson03Hints = LessonHints(
  concept:
      'When several key squares are available, compare them with the defending king. '
      'The best target is often the one the defender has the greatest difficulty reaching.',
  visual:
      'The key squares for the pawn on b4 are a6, b6, and c6. '
      'Compare their distance from the black king on f8.',
  targeted:
      'Do not head toward the defender. Build your king route toward the queenside key square that is farthest from Black.',
);

final LessonHints keySquaresLesson04Hints = LessonHints(
  concept:
      'Key squares depend on the current pawn structure. When a pawn moves, recalculate the key-square zone instead of relying on the old one.',
  visual:
      'The pawn on g2 uses f4, g4, and h4. If that pawn reaches g3, its key squares become f5, g5, and h5.',
  targeted:
      'Watch Black\'s h-pawn and prepare for the moment when changing the white pawn structure brings the new key squares closer to your king.',
);

final LessonHints pawnTragicomedyLesson05Hints = LessonHints(
  concept:
      'Losing a pawn does not automatically mean losing the game. Evaluate the position that remains before deciding the result.',
  visual:
      'Look beyond the d5-pawn: compare both kings and the remaining black d-pawn after exchanges become possible.',
  targeted:
      'Before resigning, calculate the king-and-pawn ending that remains if the d5-pawn falls.',
);

final LessonHints pawnTragicomedyLesson06Hints = LessonHints(
  concept:
      'In technical endings, every rook move can change the enemy king\'s access. Check the opponent\'s most forcing king move first.',
  visual:
      'Focus on the black king on g6 and the route toward g5 before moving the white rook.',
  targeted:
      'Avoid an automatic rook move that gives Black immediate king penetration; calculate ...Kg5 before committing the rook.',
);
