import '../domain/lesson_hints.dart';

/// Verified curriculum hints for Pawn Endgames.
///
/// These hints belong to the teaching curriculum.
/// They are not generated by Stockfish.
final LessonHints keySquaresLesson01Hints = LessonHints(
  concept:
      'A key square is a square whose occupation by the king guarantees the '
      'desired theoretical result. Focus on reaching a key square rather than '
      'simply advancing the pawn.',
  visual:
      'Look at the three key squares in front of the pawn: c6, d6, and e6. '
      'The white king on d5 has not reached one of them yet.',
  targeted:
      'Your objective is to get the white king onto c6, d6, or e6. '
      'Consider how the side to move affects whether Black can prevent that.',
);

final LessonHints keySquaresLesson02Hints = LessonHints(
  concept:
      'A non-rook pawn on the fifth rank has six key squares. Reaching one '
      'establishes the theoretical win, but the conversion still has to be played accurately.',
  visual:
      'For the pawn on b5, look at a6, b6, c6, a7, b7, and c7. '
      'Notice that the white king is already standing on b6, inside the key-square zone.',
  targeted:
      'Do not search for a key square from scratch: White already occupies one. '
      'Now look for the king route that keeps control while avoiding defensive resources.',
);
